### ISSUE TITLE
Password-validation in register page

### ISSUE THREAD

**Issue by JimJimlin** [OpenISDM/VMS-frontend#23]
Hi, from now, I still can't confirm password,  I develop on my repo and branch is 'improve-input-form' if you want to take a look. I will still on the work.

I think my problem that is I can't use custom directive into Controller.

Ref:
A plnkr example - http://plnkr.co/edit/FipgiTUaaymm5Mk6HIfn?p=preview
A stackoverflow example - http://stackoverflow.com/questions/14012239/password-check-directive-in-angularjs

**Comment by ymhuang0808** [comment]
The issue will be fixed on next PR.
