### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by chinlam91** [OpenISDM/VMS-frontend#3]
Change the code style .
1. css (all style must be create on css)
2. html (component using , like label -> panel is more suitable)

**Comment by ymhuang0808** [comment]
I think `<label>` tags which are not in `<form>` tags may be changed into `<span>` or others.

**Comment by ymhuang0808** [comment]
Why panel is more suitable ? @JimJimlin ,please joint the issue.

**Comment by chinlam91** [comment]
That's right , i'm wrong mean . Is <span>

**Comment by ymhuang0808** [comment]
:+1:

**Comment by ymhuang0808** [comment]
@chinlam91 If you fix the issue, please close the issue.

**Comment by chinlam91** [comment]
Noted
