### ISSUE TITLE
General - audit

### ISSUE THREAD

**Issue by leahwchang** [OpenISDM/VMS-frontend#37]
Hi, the below evernote link is the complete site audit:
https://www.evernote.com/l/AlW75QQg3WRJvJ7N1jZgmivTYjzIjG8xkHw

General:
- a "back" or "cancel" button would be helpful for navigation: after each form/editing profiles/viewing proposals/etc
- has notification when switching roles, but unclear which “role” users are in the current profile: specify the "role"
- include social channels (if any)

**Comment by ymhuang0808** [comment]
Thanks for your, @leahwchang  review.
If there is a current role item in the 切換身份 or avatar image dropdown, does it make users clear which role they are?

**Comment by leahwchang** [comment]
Yes, showing the current role item or an avatar image dropdown would help clarify roles for users. Thanks!

**Comment by leahwchang** [comment]
Yes, for example: list "身份: 志工" instead of "切換身份" or use an avatar/highlight the current role in dropdown menu would help clarify roles for users. 
Thanks!
