### ISSUE TITLE
Language support: English 

### ISSUE THREAD

**Issue by yuchenglin** [OpenISDM/VMS-frontend#45]
I got incorrect error messages when my system default language is English. 
`http://openisdm.github.io/volunteer/assets/lang/locale-en-US.json 404 (Not Found)`

**Comment by ymhuang0808** [comment]
We need a volunteer for English translation. 🉑 ❓

**Comment by yuchenglin** [comment]
Of course 🤓

**Comment by ymhuang0808** [comment]
fix #50
